services:
  - type: web
    name: ai-pokedex
    env: python
    buildCommand: pip install torch torchvision --index-url https://download.pytorch.org/whl/cpu && pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: DATASET_PATH
        value: /opt/render/project/src/dataset
    # Increase memory if needed for PyTorch
    plan: free
